export interface GuiTexDiagnostic { level: "info" | "warning" | "error"; message: string; index?: number; line?: number; column?: number; }
export interface GuiTexCompileResult { status?: "completed" | "failed" | "blocked"; pdfUrl?: string; pdfBase64?: string; bytes?: Uint8Array | ArrayBuffer; log?: string; diagnostics?: Array<GuiTexDiagnostic | string>; duration?: number; }
export interface GuiTexCompiler { compile(source: string, options: { engine: string; safeMode: boolean; timeout: number; packages: string[] }): Promise<GuiTexCompileResult>; }
export function escapeTex(value: unknown): string;
export function validateTex(source: string, options?: { safeMode?: boolean }): GuiTexDiagnostic[];
export class GuiTexDocument extends EventTarget { constructor(source?: string, options?: { engine?: string; safeMode?: boolean; timeout?: number; packages?: string[] }); readonly source: string; readonly options: { engine: string; safeMode: boolean; timeout: number; packages: string[] }; readonly result: GuiTexCompileResult | null; setSource(source: string, options?: { reason?: string }): boolean; setOptions(options: Partial<{ engine: string; safeMode: boolean; timeout: number; packages: string[] }>): void; diagnostics(options?: { safeMode?: boolean }): GuiTexDiagnostic[]; compile(compiler: GuiTexCompiler, options?: Partial<{ engine: string; safeMode: boolean; timeout: number; packages: string[] }>): Promise<GuiTexCompileResult | null>; toJSON(): Record<string, unknown>; }
export class GuiTexBridgeCompiler implements GuiTexCompiler { constructor(bridge: { invoke(method: string, params?: unknown): Promise<GuiTexCompileResult> }, options?: { method?: string }); compile(source: string, options: { engine: string; safeMode: boolean; timeout: number; packages: string[] }): Promise<GuiTexCompileResult>; }
export class GuiTexTemplate { constructor(source?: string); render(values?: Record<string, unknown>, options?: { raw?: string[] }): string; compile(values: Record<string, unknown>, compiler: GuiTexCompiler, options?: Record<string, unknown>): Promise<GuiTexCompileResult | null>; }
export class GuiTexEditor extends HTMLElement { documentModel: GuiTexDocument; compiler?: GuiTexCompiler; source: string; compile(): Promise<GuiTexCompileResult | null>; }
export class GuiTexPdfPreview extends HTMLElement { result: GuiTexCompileResult | null; }
export const texModule: Readonly<{ id: "tex"; version: "0.2.0"; description: string; dependencies: readonly string[]; components: readonly ["gui-tex-editor", "gui-tex-pdf-preview"]; setup(): Record<string, unknown> }>;
