export interface GuiEditorField { name: string; label?: string; group?: string; type?: string; default?: unknown; options?: Array<string | { value: string; label: string }>; min?: number; max?: number; description?: string; readOnly?: boolean; }
export class GuiEditorHistory extends EventTarget { constructor(options?: { limit?: number }); readonly canUndo: boolean; readonly canRedo: boolean; push(value: unknown): void; undo(current: unknown): unknown; redo(current: unknown): unknown; snapshot(): { undo: number; redo: number }; }
export function formatStructuredText(value: unknown, format?: "json" | string): string;
export class GuiCodeEditor extends HTMLElement { value: string; language: string; focus(): void; format(): boolean; find(query: string): number; }
export class GuiStructuredEditor extends HTMLElement { value: string; data: unknown; mode: "tree" | "text"; }
export class GuiRichTextEditor extends HTMLElement { value: string; readonly markdown: string; exec(command: string, value?: string): void; }
export class GuiPropertyInspector extends HTMLElement { schema: GuiEditorField[]; value: Record<string, unknown>; reset(name: string): boolean; }
export class GuiImageEditor extends HTMLElement { source: string; readonly state: { rotate: number; brightness: number; contrast: number; annotations: Array<{ id: string; x: number; y: number; text: string }> }; load(source: string): Promise<boolean>; rotate(degrees?: number): void; addAnnotation(annotation: { id?: string; x: number; y: number; text?: string }): void; export(type?: string): string | undefined; }
export class GuiQueryEditor extends HTMLElement { value: string; parameters: Array<{ name: string; label?: string; value?: string }>; suggestions: string[]; validate(options?: { allowWrite?: boolean }): { valid: boolean; error: string | null }; }
export interface GuiTimelineTrack { id: string; label?: string; keyframes?: Array<{ id?: string; time: number; value: unknown }>; }
export class GuiTimelineModel extends EventTarget { constructor(tracks?: GuiTimelineTrack[]); readonly tracks: GuiTimelineTrack[]; setTracks(tracks: GuiTimelineTrack[]): void; addKeyframe(trackId: string, keyframe: { id?: string; time: number; value: unknown }): boolean; moveKeyframe(trackId: string, keyframeId: string, time: number, options?: { snap?: number }): boolean; }
export class GuiTimelineEditor extends HTMLElement { model: GuiTimelineModel; playhead: number; }
export interface GuiDiagramData { shapes: Array<{ id: string; label?: string; type?: string; x: number; y: number; width?: number; height?: number }>; links: Array<{ id: string; from: string; to: string; label?: string }>; }
export class GuiDiagramModel extends EventTarget { constructor(data?: Partial<GuiDiagramData>); readonly shapes: GuiDiagramData["shapes"]; readonly links: GuiDiagramData["links"]; set(data?: Partial<GuiDiagramData>): void; addShape(shape: Omit<GuiDiagramData["shapes"][number], "id"> & { id?: string }): string; connect(from: string, to: string, options?: { id?: string; label?: string }): string; toJSON(): GuiDiagramData; }
export class GuiDiagramEditor extends HTMLElement { model: GuiDiagramModel; }
export class GuiThemeEditor extends HTMLElement { tokens: Record<string, string>; apply(target?: HTMLElement): void; }
export class GuiTranslationEditor extends HTMLElement { catalogs: Record<string, Record<string, unknown>>; setLocales(source: string, target: string): void; missing(): string[]; }
export const editorsModule: Readonly<{ id: "editors"; version: "0.1.0"; description: string; dependencies: readonly ["core"]; components: readonly string[]; setup(): Record<string, unknown> }>;
declare global { interface HTMLElementTagNameMap { "gui-rich-text-editor": GuiRichTextEditor; "gui-code-editor": GuiCodeEditor; "gui-structured-editor": GuiStructuredEditor; "gui-property-inspector": GuiPropertyInspector; "gui-image-editor": GuiImageEditor; "gui-query-editor": GuiQueryEditor; "gui-timeline-editor": GuiTimelineEditor; "gui-diagram-editor": GuiDiagramEditor; "gui-theme-editor": GuiThemeEditor; "gui-translation-editor": GuiTranslationEditor; } }
