export function contrastRatio(foreground: string, background: string): number | null;
export class GuiThemeStudio extends EventTarget { constructor(options?: { tokens?: Record<string, string>; presets?: Record<string, Record<string, string>> }); tokens: Record<string, string>; presets: Record<string, Record<string, string>>; set(name: string, value: string): this; savePreset(name: string): Record<string, string>; applyPreset(name: string): Record<string, string>; audit(pairs?: Array<{ foreground: string; background: string; label?: string }>): Array<{ label: string; ratio: number | null; aa: boolean; aaa: boolean }>; exportCss(selector?: string): string; }
export class GuiResponsiveLayout extends EventTarget { constructor(options?: { breakpoints?: Record<string, number>; items?: object[] }); breakpoints: Record<string, number>; place(item: { id: string; [key: string]: unknown }): object; move(id: string, patch: object): object; resolve(width: number): { breakpoint: string; items: object[] }; toJSON(): object; }
export class GuiDataConnectorRegistry extends EventTarget { register(definition: { id: string; load(context: object): Promise<unknown>; [key: string]: unknown }): this; list(): object[]; load(id: string, context?: object): Promise<unknown>; }
export function createReplayConnector(id: string, frames?: unknown[]): { id: string; type: string; load(context?: { index?: number }): Promise<unknown> };
export class GuiCredentialVault extends EventTarget { constructor(adapter: { get(reference: string, options?: object): Promise<unknown>; set(reference: string, value: unknown, options?: object): Promise<void>; remove?(reference: string): Promise<void> }); set(reference: string, value: unknown, options?: object): Promise<void>; get(reference: string, options?: object): Promise<unknown>; remove(reference: string): Promise<void>; test(reference: string, tester: (value: unknown) => unknown): Promise<unknown>; }
export class GuiObservabilityHub extends EventTarget { constructor(options?: { limit?: number; alerts?: object[] }); metric(name: string, value: number, tags?: object): object; trace(name: string, context?: object): { trace: object; span(name: string, attributes?: object): { end(result?: object): object } }; snapshot(): object; }
export class GuiNodeLibrary { constructor(nodes?: object[]); register(node: { type: string; [key: string]: unknown }): this; create(type: string, patch?: object): object; list(): object[]; }
export class GuiFlowDebugger extends EventTarget { constructor(options?: { breakpoints?: string[] }); breakpoints: Set<string>; events: object[]; paused: boolean; toggleBreakpoint(nodeId: string): boolean; step(nodeId: string, values?: object): object; resume(): void; }
export function fftMagnitude(samples: Iterable<number>): Array<{ frequency: number; magnitude: number }>;
export function correlation(left: Iterable<number>, right: Iterable<number>): number | null;
export function exportDelimited(rows: object[], options?: { columns?: string[] | null; delimiter?: string }): string;
export function exportChartSvg(series: Iterable<number | { x?: number; y: number }>, options?: { width?: number; height?: number; stroke?: string }): string;
export function normalizeAnalysisDataset(type: "scatter" | "heatmap" | "candlestick", values?: object[]): object[];
export class GuiAccessibilityLab extends EventTarget { constructor(options?: { reducedMotion?: boolean }); reducedMotion: boolean; focusPlan(elements: Array<{ id?: string; label?: string; disabled?: boolean; hidden?: boolean; tabIndex?: number; order?: number }>): { valid: boolean; order: string[] }; motion(options?: { duration?: number; easing?: string }): { duration: number; easing: string; disabled: boolean }; colorVision(color: string, mode?: string): { color: string; mode: string; multipliers: number[] }; }
export class GuiCachePolicy { constructor(rules?: Array<{ match: string; strategy: string }>) ; rules: object[]; resolve(url: string | { pathname?: string }, fallback?: string): object; }
export class GuiServiceWorkerBridge extends EventTarget { constructor(options?: { navigatorRef?: object }); registration: unknown; register(url: string, options?: object): Promise<unknown>; message(payload: object): Promise<void>; }
export class GuiOfflineSyncQueue extends EventTarget { constructor(options?: { storage?: { get(key: string): Promise<unknown>; set(key: string, value: unknown): Promise<void> }; key?: string; limit?: number }); operations: object[]; restore(): Promise<object[]>; enqueue(operation: object): Promise<object>; flush(send: (operation: object) => Promise<void>): Promise<object[]>; snapshot(project: object): string; import(snapshot: string | object): object; }
export class GuiPluginPolicy { constructor(options?: { apiVersion?: string; permissions?: string[]; verifySignature?: (manifest: object) => Promise<boolean> }); verify(manifest: object): Promise<{ valid: boolean; reasons: string[]; sandbox: string }>; scaffold(options: { id: string; name: string; version?: string }): object; }
export class GuiVisualRegressionSuite extends EventTarget { constructor(options?: { viewports?: number[]; themes?: string[]; locales?: string[] }); matrix(component: string): Array<{ id: string; component: string; width: number; theme: string; locale: string }>; baseline(id: string, image: unknown): void; compare(id: string, image: unknown, comparator: (baseline: unknown, image: unknown) => Promise<{ passed: boolean; [key: string]: unknown }>): Promise<object>; }
export class GuiProductionOptimizer extends EventTarget { constructor(options?: { budgets?: Record<string, number> }); setBudget(asset: string, bytes: number): this; evaluateAssets(assets: Record<string, number>): Array<{ asset: string; bytes: number; budget: number | null; passed: boolean }>; registerLazyElement(name: string, loader: () => Promise<unknown>): this; loadElement(name: string): Promise<CustomElementConstructor>; }
export class GuiThemeStudioEditor extends HTMLElement { studio: GuiThemeStudio; }
export class GuiLayoutDesigner extends HTMLElement { layout: GuiResponsiveLayout; }
export class GuiConnectorManager extends HTMLElement { connectors: GuiDataConnectorRegistry; }
export class GuiObservabilityDashboard extends HTMLElement { hub: GuiObservabilityHub; }
export class GuiVisualRegressionPanel extends HTMLElement { suite: GuiVisualRegressionSuite; }
export const productionModule: { id: string; version: string; description: string; dependencies: string[]; elements: string[] };
