import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { safeIdentifier } from "./dx-utils.mjs";

const TYPE_MAP = Object.freeze({ string: "string", number: "number", boolean: "boolean", unknown: "unknown", void: "void" });
function jsType(type) { return TYPE_MAP[type] ?? safeIdentifier(type, "unknown"); }
function csharpType(type) {
  return { string: "string", number: "double", boolean: "bool", void: "void", unknown: "object" }[type] ?? safeIdentifier(type, "object");
}
function pythonType(type) { return { string: "str", number: "float", boolean: "bool", void: "None", unknown: "object" }[type] ?? safeIdentifier(type, "object"); }
function parameters(method, mapper) {
  return Object.entries(method.params ?? {}).map(([name, type]) => `${safeIdentifier(name, "value").replace(/^./, (char) => char.toLowerCase())}: ${mapper(type)}`);
}

export function validateBridgeSpec(spec) {
  if (!spec || typeof spec !== "object") throw new TypeError("Bridge specification must be an object.");
  if (!Array.isArray(spec.methods) || !spec.methods.length) throw new TypeError("Bridge specification requires a non-empty methods array.");
  const ids = new Set();
  for (const method of spec.methods) {
    if (!/^[a-z][a-z0-9]*(?:[.:][a-z][a-z0-9]*)*$/.test(method.id ?? "")) throw new TypeError(`Invalid bridge method id: ${method.id}`);
    if (ids.has(method.id)) throw new TypeError(`Duplicate bridge method id: ${method.id}`);
    ids.add(method.id);
  }
  return true;
}

export function generateBridgeArtifacts(spec) {
  validateBridgeSpec(spec);
  const namespace = safeIdentifier(spec.namespace, "AppBridge");
  const methods = spec.methods.map((method) => ({ ...method, name: safeIdentifier(method.name ?? method.id.split(/[.:]/).pop(), "invoke") }));
  const declarations = `// Generated by GuiKit. Do not edit.\nexport interface ${namespace} {\n${methods.map((method) => `  ${method.name[0].toLowerCase() + method.name.slice(1)}(params: { ${Object.entries(method.params ?? {}).map(([name, type]) => `${name}: ${jsType(type)}`).join("; ")} }): Promise<${jsType(method.result ?? "unknown")}>;`).join("\n")}\n}\n`;
  const mock = `// Generated by GuiKit. Override handlers in tests.\nexport function create${namespace}Mock(handlers = {}) {\n  return { invoke(method, params) {\n    const handler = handlers[method];\n    if (!handler) return Promise.reject(new Error(\`No mock handler for \${method}\`));\n    return Promise.resolve(handler(params));\n  } };\n}\n`;
  const python = `# Generated by GuiKit. Do not edit.\nfrom typing import Protocol\n\nclass ${namespace}(Protocol):\n${methods.map((method) => { const args = parameters(method, pythonType); return `    async def ${method.name[0].toLowerCase() + method.name.slice(1)}(self${args.length ? `, ${args.join(", ")}` : ""}) -> ${pythonType(method.result ?? "unknown")}: ...`; }).join("\n") || "    pass"}\n`;
  const csharp = `// Generated by GuiKit. Do not edit.\nusing System.Threading.Tasks;\n\nnamespace ${namespace};\n\npublic interface I${namespace}\n{\n${methods.map((method) => `    Task<${csharpType(method.result ?? "unknown")}> ${method.name}Async(${Object.entries(method.params ?? {}).map(([name, type]) => `${csharpType(type)} ${safeIdentifier(name, "value")}`).join(", ")});`).join("\n")}\n}\n`;
  return { "bridge-client.d.ts": declarations, "bridge-mock.js": mock, "bridge-python.py": python, "BridgeContracts.cs": csharp };
}

export async function generateBridgeFiles(specFile, outputDirectory) {
  const spec = JSON.parse(await readFile(specFile, "utf8"));
  const artifacts = generateBridgeArtifacts(spec);
  await mkdir(outputDirectory, { recursive: true });
  await Promise.all(Object.entries(artifacts).map(([name, content]) => writeFile(path.join(outputDirectory, name), content)));
  return Object.keys(artifacts).map((name) => path.join(outputDirectory, name));
}
