import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

function walkTokens(value, prefix = [], output = []) {
  if (value && typeof value === "object" && "$value" in value) {
    output.push({ name: prefix.join("-"), value: value.$value, type: value.$type ?? "other" });
  } else if (value && typeof value === "object") {
    Object.entries(value).filter(([key]) => !key.startsWith("$")).forEach(([key, child]) => walkTokens(child, [...prefix, key], output));
  }
  return output;
}
export function flattenTokens(tokens) { return walkTokens(tokens); }
export function generateTokenArtifacts(tokens) {
  const entries = flattenTokens(tokens);
  const css = `/* Generated by GuiKit from design tokens. */\n:root {\n${entries.map((entry) => `  --gui-${entry.name}: ${entry.value};`).join("\n")}\n}\n`;
  const figma = JSON.stringify({ collections: [{ name: "GuiKit", modes: [{ name: "Default", values: entries }] }] }, null, 2) + "\n";
  return { "guikit.tokens.css": css, "guikit.figma-variables.json": figma };
}
export async function generateTokenFiles(tokenFile, outputDirectory) {
  const artifacts = generateTokenArtifacts(JSON.parse(await readFile(tokenFile, "utf8")));
  await mkdir(outputDirectory, { recursive: true });
  await Promise.all(Object.entries(artifacts).map(([name, content]) => writeFile(path.join(outputDirectory, name), content)));
  return Object.keys(artifacts).map((name) => path.join(outputDirectory, name));
}
